name = "devsocial-push"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
VAPID_SUBJECT = "mailto:admin@akdavid.dev"

# Run: wrangler kv:namespace create "PUSH_SUBSCRIPTIONS"
# Then update the id below

[[kv_namespaces]]
binding = "PUSH_SUBSCRIPTIONS"
id = "7f795b8d66b9411a99c168790f16db11"
